version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      DB_HOST: 'database'
    depends_on:
      - database
    networks:
      - ddd-start

  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
    volumes:
      - './src/sql:/docker-entrypoint-initdb.d'
    networks:
      - ddd-start


networks:
  ddd-start:
    driver: bridge
